# execute via : sudo ansible-playbook standard-desktop.yml
- hosts: active
  become: true
  tasks:
  - name: Install base KDE Plasma and display manager
    apt:
      name:
         - kubuntu-desktop
         - sddm
 
      install_recommends: no
      state: latest
      update_cache: yes
      cache_valid_time: 100000
  - name: Install deb packages from standard repositories
    apt: 
      name:
        ##      Security Software     ##

        # AV software - removed for now - shouldn't be needed for a desktop.
        #- clamav
        #- clamtk

 sudo apt install apt-transport-https curl

sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update

sudo apt install brave-browser

https://www.linuxmadesimple.info/2020/11/how-to-install-brave-browser-on-ubuntu.html